### ISSUE TITLE
[Errno 8] Exec format error

### ISSUE THREAD

**Issue by XiaoshanLin9701** [gaoqitong/LTL2FullProd#1]
The code throws the following issue:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by XiaoshanLin9701** [comment]
**It turns out that the ltl2ba binary is not executable in ubuntu. I found the source code of ltl2ba on http://www.lsv.fr/~gastin/ltl2ba/ and replace the original ltl2ba binary with the new binary generated by the source code. Then this package works pretty well. Thanks!**
