### ISSUE TITLE
Cannot execute binary file "ltl2ba": Exec format error when running domo.py

### ISSUE THREAD

**Issue by ziji-wu** [gaoqitong/LTL2FullProd#2]
Sorry to bother. I want to use this repo in my project, and I just downloaded it and copied into my project. Then when I try to run demo.py, this error occured,
`OSError: [Errno 8] Exec format error: '/home/user/桌面/hpcl.wu/projs/TAMP_imple_wu/LTL2FullProd/ltl2ba'`

As I am using Python 3.7 conda virtual envs on Ubuntu 20.04, so I migrated this repo from python2 to python3, change the python interupter to conda virtual path, then reconstruct a new binrary file 'ltl2ta' and replaced the old using command
`pyinstaller -F ltl2ba.py &&
chmod +x ltl2ba
`

Then when I running demo.py again, it's still the error:
`OSError: [Errno 8] Exec format error: '/home/user/桌面/hpcl.wu/projs/TAMP_imple_wu/LTL2FullProd/ltl2ba'`

So I want to try ''ltl2ba' directly, in terminal I tried a simple example `./ltl2ba "<>roll"`, as I noticed '-f' is not a parm so I didn't use './ltl2ba -f "<>roll"' like ltl2ba.py, otherwise this error occured "ltl2ba: error: unrecognized arguments: -f", however, thougn without -f parm, new question stiil:
`Namespace(LTL='<>roll') 
Traceback (most recent call last):
  File "ltl2ba.py", line 34, in <module>
    ltl2ba_output = run_ltl2ba(args.LTL)
  File "ltl2ba.py", line 14, in run_ltl2ba
    raw_output = check_output([ltl2ba, "-f", "%s" % formula])
  File "subprocess.py", line 411, in check_output
  File "subprocess.py", line 488, in run
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1551, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIPaJ2oz/ltl2ba_copy': '/tmp/_MEIPaJ2oz/ltl2ba_copy'
[48316] Failed to execute script 'ltl2ba' due to unhandled exception!
`

I have no idea why this happens? and how to solve it? Consider line 13 and line 30 in `ltl2ba.py`, main called function `run_ltl2ba` and then funt `run_ltl2ba` called binary file 'ltl2ba' using a subprocess, is it a dead lock? and what about the `-f` parm, it seems not be defined in `ltl2ba.py`?

**Comment by ziji-wu** [comment]
PS: One possible reason may be the chinese contained path of `ltl2ba`, however, I got the same error after changing a non-chinese path.

**Comment by ziji-wu** [comment]
Oops! A fatal mistake I made. May I should search more info from the internet. I solved this problem by download the `ltl2ba` source code written by C at this [website](http://www.lsv.fr/~gastin/ltl2ba/), then `make` and get a new `ltl2ba` binary file and replace the older one. By the way, a python repo `networkx 1.11` is needed, if version of `networkx` > 1.11, other errors may occcured.

**Comment by ziji-wu** [comment]
Correct: `networkx 1.10` is needed, otherwise graph plot part have new issues
